[user]
name = "fredrikr79"
email = "fredrikrobertsen7@gmail.com"

[ui]
paginate = "auto"
default-command = "status"
editor = "nvim"

[ui.streampager]
interface = "quit-quickly-or-clear-output"

[[--scope]]
--when.commands = ["status"]
[--scope.ui]
paginate = "never"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[aliases]
l = ["log", "-r", "(main..@):: | (main..@)-"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
e = ["edit"]
r = ["rebase"]
s = ["squash"]
si = ["squash", "--interactive"]
flip = ["util", "exec", "--", "nu", "-c", "jj rebase --quiet --revisions @- --insert-after @; jj edit @+ --quiet; jj status"]
